"""empty message

Revision ID: e40657bfa333
Revises: 822be35775b5
Create Date: 2019-12-04 14:19:38.311316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40657bfa333'
down_revision = '822be35775b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
