"""empty message

Revision ID: f60407e8dea1
Revises: f3605ef778b7
Create Date: 2019-12-04 20:10:25.373351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60407e8dea1'
down_revision = 'f3605ef778b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('upvote', sa.Integer(), nullable=True),
    sa.Column('downvote', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('registered', sa.DateTime(), nullable=False))
    op.add_column('post', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('post', sa.Column('upvote', sa.Integer(), nullable=True))
    op.drop_constraint('post_name_key', 'post', type_='unique')
    op.create_unique_constraint(None, 'post', ['title'])
    op.drop_column('post', 'name')
    op.drop_column('post', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='unique')
    op.create_unique_constraint('post_name_key', 'post', ['name'])
    op.drop_column('post', 'upvote')
    op.drop_column('post', 'title')
    op.drop_column('post', 'registered')
    op.drop_table('comment')
    # ### end Alembic commands ###
